version: "3.3"
services:
  api:
    build: .
    container_name: blockchain_challenge_manager
    environment:
      - BLOCKCHAIN_URL=http://geth:8545
      - CHALLENGE=CryptoCasino
    ports:
      - 3000:3000
    secrets:
      - deployer_priv_key
    restart: "no"

secrets:
  deployer_priv_key:
    file: ./deployer_priv_key.secret.txt

networks:
  default: